[package]
name = "sserver"
version = "0.1.0"
authors = ["Dawid J. Kubis <dawid.kubis3@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.2"
comrak = "0.6.2"
structopt = "0.3.5"
git2 = "0.11.0"
toml = "0.5.5"
serde = {version="1.0.104", features=["derive"]}
anyhow = "1.0.26"
